name: 'QCloud Cos Deploy'
description: 'deploy project to cos'
inputs:
  secret_id:
    description: "qcloud secret ID"
    required: false
    default: ""
  secret_key:
    description: "qcloud secret key"
    required: false
    default: ""
  token:
    description: "qcloud ots token"
    required: false
    default: ""
  buckets:
    description: "存储桶名称"
    required: true
  region:
    description: "存储桶地域"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        wget https://github.com/tencentyun/coscli/releases/download/v0.12.0-beta/coscli-linux -O coscli
        chmod 755 coscli
        sudo mv ./coscli /usr/local/bin/
        coscli --version
      shell: bash
    - run: |  
        echo "
        cos:
          base:
            secretid: ${{ inputs.secret_id }}
            secretkey: ${{ inputs.secret_key }}
            sessiontoken: ${{ inputs.token }}
            protocol: https
          buckets:
          - name: ${{ inputs.buckets }}
            alias: ${{ inputs.buckets }}
            region: ${{ inputs.region }}
            endpoint: ${{ inputs.buckets }}.cos.${{ inputs.region }}.myqcloud.com
        " > ~/.cos.yaml
      shell: bash
